spring.application.name=user-api
server.port=8081

spring.datasource.url=jdbc:postgresql://localhost:5432/automationdb
spring.datasource.username=rajat
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

#app.security.mode=jwt
app.security.mode=${AUTH_TYPE:jwt}

spring.security.user.name=rajat
spring.security.user.password=rajat123
spring.security.user.roles=USER

app.jwt.secret=ThisIsASecretKeyForJwtTokenGenerationThisIsASecretKey12345
app.jwt.expiration-ms=3600000
app.jwt.refresh-expiration-ms=86400000

spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/automationdb}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:postgres}


management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always


spring.security.oauth2.client.registration.google.client-id=${GOOGLE_CLIENT_ID}
spring.security.oauth2.client.registration.google.client-secret=${GOOGLE_CLIENT_SECRET}
spring.security.oauth2.client.registration.google.scope=openid,email,profile