# ===============================
# Application
# ===============================
spring.application.name=user-api

# ===============================
# Server
# ===============================
server.port=8081

# ===============================
# Database
# ===============================
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/automationdb}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:postgres}

# ===============================
# JPA / Hibernate
# ===============================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

# ===============================
# Security
# ===============================
app.security.mode=${AUTH_TYPE:jwt}

# ===============================
# JWT
# ===============================
app.jwt.secret=${JWT_SECRET:ThisIsASecretKeyForJwtTokenGenerationThisIsASecretKey12345}
app.jwt.expiration-ms=${JWT_EXPIRATION_MS:3600000}
app.jwt.refresh-expiration-ms=${JWT_REFRESH_EXPIRATION_MS:86400000}


# ===============================
# Client Credentials
# ===============================
app.client-auth.client-id=${CLIENT_AUTH_ID:rest-assured-client}
app.client-auth.client-secret=${CLIENT_AUTH_SECRET:secret123}

# ===============================
# Actuator
# ===============================
management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always

# ===============================
# Swagger / OpenAPI
# ===============================
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
